version: '3.4'
services:
  redis:
    platform: linux/x86_64
    image: grokzen/redis-cluster:6.2.10
    ports:
      - "7000-7005:7000-7005"
    environment:
      REDIS_CLUSTER_IP: 0.0.0.0
      IP: 0.0.0.0
      STANDALONE: 'true'
