version: '3.4'
services:
  redis:
    image: grokzen/redis-cluster
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    environment:
      REDIS_CLUSTER_IP: 0.0.0.0
      IP: 0.0.0.0
      STANDALONE: 'true'
